version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
  - package-ecosystem: npm
    directory: '/functions'
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
